export const authorizedMethodology = [
  ["01", "Authorization checkpoint", "Confirm written approval, defined scope, exclusions, rate limits, and stop conditions."],
  ["02", "Asset inventory", "Review only client-approved domains, APIs, applications, and environments."],
  ["03", "Passive discovery", "Collect permitted, non-intrusive intelligence from approved sources."],
  ["04", "DNS and reachability", "Resolve approved assets within the agreed request budget."],
  ["05", "HTTP observation", "Record permitted responses, redirects, headers, and service metadata."],
  ["06", "Technology inventory", "Identify frameworks and components for remediation context."],
  ["07", "Attack-surface review", "Map approved routes, APIs, and client-provided workflows."],
  ["08", "Authentication review", "Assess documented authentication controls without credential capture."],
  ["09", "Authorization review", "Review object and tenant-boundary controls with human oversight."],
  ["10", "Input-handling review", "Assess validation and output handling through safe, approved checks."],
  ["11", "Session-control review", "Review session lifecycle, logout, and token-handling design."],
  ["12", "Data-exposure review", "Identify unnecessary exposure using sanitized evidence only."],
  ["13", "API contract review", "Compare approved API behavior with documented authorization expectations."],
  ["14", "Client-side review", "Review browser-visible controls and security headers safely."],
  ["15", "RAG source-trust review", "Assess source provenance, retrieval boundaries, and data classification."],
  ["16", "Prompt-injection resilience", "Run benign, customer-approved boundary test cases only."],
  ["17", "Tool-permission review", "Evaluate least privilege, approval points, and tool constraints."],
  ["18", "Human-approval review", "Confirm human-in-the-loop checks for consequential AI actions."],
  ["19", "Logging and detection", "Review auditability, alerting, and privacy-safe telemetry."],
  ["20", "Finding correlation", "Collect sanitized evidence and deduplicate candidate findings."],
  ["21", "Independent validation", "Require a separate human validation decision before reporting."],
  ["22", "Remediation and retest", "Assign fixes, record retest outcomes, and close explicitly."],
] as const;
